### ISSUE TITLE
ICS Advisory (ICSA-21-119-04)

### ISSUE THREAD

**Issue by mek363** [weston-embedded/uC-OS2#10]
Is the current version provided here susceptible to the vulnerability described here?
https://us-cert.cisa.gov/ics/advisories/icsa-21-119-04

It references "Micrium uCOS II/uCOS III Versions 1.39.0 and prior". This is a very old version, or is this a typo, or is it referring to a sub-module?

Thanks for your help sorting this out.

**Comment by forg0ne** [comment]
We've contacted the agency regarding this vulnerability.
It seems there was a mixup with the product names.
This actually affects the uC/LIB module and has been patched in the latest release.
The issue was logged [here](https://github.com/weston-embedded/uC-LIB/issues/3).
