### ISSUE TITLE
file "cpu.h" is missing...

### ISSUE THREAD

**Issue by gthaker** [weston-embedded/uC-OS2#15]
I am interested in   ports/PowerPC/*    ports. All of these (and in fact many other ports) all refer to a   file "cpu.h" that I can't find anywhere in the repo. I tried to search this situation on google but can't find any solution. 

Where would one find this file? I am using GNU gcc toolchain for ppc 32 bits big endian  to do my compiling - no file cpu.h in that toolchain either.

**Comment by forg0ne** [comment]
Check the uC/CPU repository:
https://github.com/weston-embedded/uC-CPU
