### ISSUE TITLE
Critical section issue in OSTimeTick

### ISSUE THREAD

**Issue by lllbbbyyy** [weston-embedded/uC-OS2#22]
In the OSTimeTick function, is there some problem with where the critical section function is used?:https://github.com/weston-embedded/uC-OS2/blob/8fa5341eda1daf4ab104f47c3761a45d60a2452f/Source/os_core.c#L985
I think the critical section should be placed above this line:https://github.com/weston-embedded/uC-OS2/blob/22a9ded73d7352110be0996708f1ed0e9c4621f0/Source/os_core.c#L983
Otherwise, when the current task obtains the OSTCBList, it may be interrupted before entering the critical section, and then the OSTCBList is changed. At this time, the OSTCBList used later will be wrong.

**Comment by forg0ne** [comment]
I don't see a problem here.
OSTimeTick is called from interrupt context, so task switches should not be taking place.
