### ISSUE TITLE
the problem of the OS_CORE.C file

### ISSUE THREAD

**Issue by Abandon339** [weston-embedded/uC-OS2#4]
in the os_core.c, the line 1919, `usage  = 100 - (INT8S)(OSIdleCtrRun / OSIdleCtrMax);`
`OSCPUUsage = 100 *(1- OSIdleCtr / OSIdleCtrMax)`   Isn't that the formula you provided?

**Comment by forg0ne** [comment]
The reason for this discrepancy is that OSIdleCtrMax is divided by 100 earlier in the function. If you account for this, the expressions are equivalent.
